/*
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.ui;

import assignment_2_ssda.xtext_ml.ass2.ui.internal.Ass2Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Ass2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Ass2Activator activator = Ass2Activator.getInstance();
		return activator != null ? activator.getInjector(Ass2Activator.ASSIGNMENT_2_SSDA_XTEXT_ML_ASS2_MYDSL) : null;
	}

}
