/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl.impl;

import assignment_2_ssda.xtext_ml.ass2.myDsl.Genital_thrush;
import assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Genital thrush</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Genital_thrushImpl extends SymptomImpl implements Genital_thrush
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Genital_thrushImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.GENITAL_THRUSH;
  }

} //Genital_thrushImpl
