/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl.impl;

import assignment_2_ssda.xtext_ml.ass2.myDsl.J48Classifier;
import assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>J48 Classifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.J48ClassifierImpl#getSet_pruned_trees <em>Set pruned trees</em>}</li>
 * </ul>
 *
 * @generated
 */
public class J48ClassifierImpl extends Machine_learning_AlgorithmsImpl implements J48Classifier
{
  /**
   * The default value of the '{@link #getSet_pruned_trees() <em>Set pruned trees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSet_pruned_trees()
   * @generated
   * @ordered
   */
  protected static final String SET_PRUNED_TREES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSet_pruned_trees() <em>Set pruned trees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSet_pruned_trees()
   * @generated
   * @ordered
   */
  protected String set_pruned_trees = SET_PRUNED_TREES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected J48ClassifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.J48_CLASSIFIER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSet_pruned_trees()
  {
    return set_pruned_trees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSet_pruned_trees(String newSet_pruned_trees)
  {
    String oldSet_pruned_trees = set_pruned_trees;
    set_pruned_trees = newSet_pruned_trees;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.J48_CLASSIFIER__SET_PRUNED_TREES, oldSet_pruned_trees, set_pruned_trees));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.J48_CLASSIFIER__SET_PRUNED_TREES:
        return getSet_pruned_trees();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.J48_CLASSIFIER__SET_PRUNED_TREES:
        setSet_pruned_trees((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.J48_CLASSIFIER__SET_PRUNED_TREES:
        setSet_pruned_trees(SET_PRUNED_TREES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.J48_CLASSIFIER__SET_PRUNED_TREES:
        return SET_PRUNED_TREES_EDEFAULT == null ? set_pruned_trees != null : !SET_PRUNED_TREES_EDEFAULT.equals(set_pruned_trees);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (set_pruned_trees: ");
    result.append(set_pruned_trees);
    result.append(')');
    return result.toString();
  }

} //J48ClassifierImpl
