/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl.impl;

import assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor;
import assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines;
import assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage;
import assignment_2_ssda.xtext_ml.ass2.myDsl.Patient;
import assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test;
import assignment_2_ssda.xtext_ml.ass2.myDsl.Symptom;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Patient</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getName <em>Name</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getPatient_Gender <em>Patient Gender</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getPatient_Age <em>Patient Age</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getPatient_Height <em>Patient Height</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getPatient_Weight <em>Patient Weight</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getPatient_blood_pressure <em>Patient blood pressure</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getPulse_rate <em>Pulse rate</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getSymptoms <em>Symptoms</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getMedicines <em>Medicines</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getSugar_tests <em>Sugar tests</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl#getDOCTORS <em>DOCTORS</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PatientImpl extends MinimalEObjectImpl.Container implements Patient
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPatient_Gender() <em>Patient Gender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Gender()
   * @generated
   * @ordered
   */
  protected static final String PATIENT_GENDER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPatient_Gender() <em>Patient Gender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Gender()
   * @generated
   * @ordered
   */
  protected String patient_Gender = PATIENT_GENDER_EDEFAULT;

  /**
   * The default value of the '{@link #getPatient_Age() <em>Patient Age</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Age()
   * @generated
   * @ordered
   */
  protected static final int PATIENT_AGE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPatient_Age() <em>Patient Age</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Age()
   * @generated
   * @ordered
   */
  protected int patient_Age = PATIENT_AGE_EDEFAULT;

  /**
   * The default value of the '{@link #getPatient_Height() <em>Patient Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Height()
   * @generated
   * @ordered
   */
  protected static final String PATIENT_HEIGHT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPatient_Height() <em>Patient Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Height()
   * @generated
   * @ordered
   */
  protected String patient_Height = PATIENT_HEIGHT_EDEFAULT;

  /**
   * The default value of the '{@link #getPatient_Weight() <em>Patient Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Weight()
   * @generated
   * @ordered
   */
  protected static final String PATIENT_WEIGHT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPatient_Weight() <em>Patient Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_Weight()
   * @generated
   * @ordered
   */
  protected String patient_Weight = PATIENT_WEIGHT_EDEFAULT;

  /**
   * The default value of the '{@link #getPatient_blood_pressure() <em>Patient blood pressure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_blood_pressure()
   * @generated
   * @ordered
   */
  protected static final int PATIENT_BLOOD_PRESSURE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPatient_blood_pressure() <em>Patient blood pressure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatient_blood_pressure()
   * @generated
   * @ordered
   */
  protected int patient_blood_pressure = PATIENT_BLOOD_PRESSURE_EDEFAULT;

  /**
   * The default value of the '{@link #getPulse_rate() <em>Pulse rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPulse_rate()
   * @generated
   * @ordered
   */
  protected static final int PULSE_RATE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPulse_rate() <em>Pulse rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPulse_rate()
   * @generated
   * @ordered
   */
  protected int pulse_rate = PULSE_RATE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSymptoms() <em>Symptoms</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSymptoms()
   * @generated
   * @ordered
   */
  protected EList<Symptom> symptoms;

  /**
   * The cached value of the '{@link #getMedicines() <em>Medicines</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMedicines()
   * @generated
   * @ordered
   */
  protected EList<Medicines> medicines;

  /**
   * The cached value of the '{@link #getSugar_tests() <em>Sugar tests</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSugar_tests()
   * @generated
   * @ordered
   */
  protected EList<Sugar_Test> sugar_tests;

  /**
   * The cached value of the '{@link #getDOCTORS() <em>DOCTORS</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDOCTORS()
   * @generated
   * @ordered
   */
  protected EList<Doctor> doctors;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PatientImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PATIENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATIENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPatient_Gender()
  {
    return patient_Gender;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPatient_Gender(String newPatient_Gender)
  {
    String oldPatient_Gender = patient_Gender;
    patient_Gender = newPatient_Gender;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATIENT__PATIENT_GENDER, oldPatient_Gender, patient_Gender));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPatient_Age()
  {
    return patient_Age;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPatient_Age(int newPatient_Age)
  {
    int oldPatient_Age = patient_Age;
    patient_Age = newPatient_Age;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATIENT__PATIENT_AGE, oldPatient_Age, patient_Age));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPatient_Height()
  {
    return patient_Height;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPatient_Height(String newPatient_Height)
  {
    String oldPatient_Height = patient_Height;
    patient_Height = newPatient_Height;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATIENT__PATIENT_HEIGHT, oldPatient_Height, patient_Height));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPatient_Weight()
  {
    return patient_Weight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPatient_Weight(String newPatient_Weight)
  {
    String oldPatient_Weight = patient_Weight;
    patient_Weight = newPatient_Weight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATIENT__PATIENT_WEIGHT, oldPatient_Weight, patient_Weight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPatient_blood_pressure()
  {
    return patient_blood_pressure;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPatient_blood_pressure(int newPatient_blood_pressure)
  {
    int oldPatient_blood_pressure = patient_blood_pressure;
    patient_blood_pressure = newPatient_blood_pressure;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATIENT__PATIENT_BLOOD_PRESSURE, oldPatient_blood_pressure, patient_blood_pressure));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPulse_rate()
  {
    return pulse_rate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPulse_rate(int newPulse_rate)
  {
    int oldPulse_rate = pulse_rate;
    pulse_rate = newPulse_rate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATIENT__PULSE_RATE, oldPulse_rate, pulse_rate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Symptom> getSymptoms()
  {
    if (symptoms == null)
    {
      symptoms = new EObjectContainmentEList<Symptom>(Symptom.class, this, MyDslPackage.PATIENT__SYMPTOMS);
    }
    return symptoms;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Medicines> getMedicines()
  {
    if (medicines == null)
    {
      medicines = new EObjectContainmentEList<Medicines>(Medicines.class, this, MyDslPackage.PATIENT__MEDICINES);
    }
    return medicines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Sugar_Test> getSugar_tests()
  {
    if (sugar_tests == null)
    {
      sugar_tests = new EObjectContainmentEList<Sugar_Test>(Sugar_Test.class, this, MyDslPackage.PATIENT__SUGAR_TESTS);
    }
    return sugar_tests;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Doctor> getDOCTORS()
  {
    if (doctors == null)
    {
      doctors = new EObjectResolvingEList<Doctor>(Doctor.class, this, MyDslPackage.PATIENT__DOCTORS);
    }
    return doctors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.PATIENT__SYMPTOMS:
        return ((InternalEList<?>)getSymptoms()).basicRemove(otherEnd, msgs);
      case MyDslPackage.PATIENT__MEDICINES:
        return ((InternalEList<?>)getMedicines()).basicRemove(otherEnd, msgs);
      case MyDslPackage.PATIENT__SUGAR_TESTS:
        return ((InternalEList<?>)getSugar_tests()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.PATIENT__NAME:
        return getName();
      case MyDslPackage.PATIENT__PATIENT_GENDER:
        return getPatient_Gender();
      case MyDslPackage.PATIENT__PATIENT_AGE:
        return getPatient_Age();
      case MyDslPackage.PATIENT__PATIENT_HEIGHT:
        return getPatient_Height();
      case MyDslPackage.PATIENT__PATIENT_WEIGHT:
        return getPatient_Weight();
      case MyDslPackage.PATIENT__PATIENT_BLOOD_PRESSURE:
        return getPatient_blood_pressure();
      case MyDslPackage.PATIENT__PULSE_RATE:
        return getPulse_rate();
      case MyDslPackage.PATIENT__SYMPTOMS:
        return getSymptoms();
      case MyDslPackage.PATIENT__MEDICINES:
        return getMedicines();
      case MyDslPackage.PATIENT__SUGAR_TESTS:
        return getSugar_tests();
      case MyDslPackage.PATIENT__DOCTORS:
        return getDOCTORS();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.PATIENT__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.PATIENT__PATIENT_GENDER:
        setPatient_Gender((String)newValue);
        return;
      case MyDslPackage.PATIENT__PATIENT_AGE:
        setPatient_Age((Integer)newValue);
        return;
      case MyDslPackage.PATIENT__PATIENT_HEIGHT:
        setPatient_Height((String)newValue);
        return;
      case MyDslPackage.PATIENT__PATIENT_WEIGHT:
        setPatient_Weight((String)newValue);
        return;
      case MyDslPackage.PATIENT__PATIENT_BLOOD_PRESSURE:
        setPatient_blood_pressure((Integer)newValue);
        return;
      case MyDslPackage.PATIENT__PULSE_RATE:
        setPulse_rate((Integer)newValue);
        return;
      case MyDslPackage.PATIENT__SYMPTOMS:
        getSymptoms().clear();
        getSymptoms().addAll((Collection<? extends Symptom>)newValue);
        return;
      case MyDslPackage.PATIENT__MEDICINES:
        getMedicines().clear();
        getMedicines().addAll((Collection<? extends Medicines>)newValue);
        return;
      case MyDslPackage.PATIENT__SUGAR_TESTS:
        getSugar_tests().clear();
        getSugar_tests().addAll((Collection<? extends Sugar_Test>)newValue);
        return;
      case MyDslPackage.PATIENT__DOCTORS:
        getDOCTORS().clear();
        getDOCTORS().addAll((Collection<? extends Doctor>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PATIENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.PATIENT__PATIENT_GENDER:
        setPatient_Gender(PATIENT_GENDER_EDEFAULT);
        return;
      case MyDslPackage.PATIENT__PATIENT_AGE:
        setPatient_Age(PATIENT_AGE_EDEFAULT);
        return;
      case MyDslPackage.PATIENT__PATIENT_HEIGHT:
        setPatient_Height(PATIENT_HEIGHT_EDEFAULT);
        return;
      case MyDslPackage.PATIENT__PATIENT_WEIGHT:
        setPatient_Weight(PATIENT_WEIGHT_EDEFAULT);
        return;
      case MyDslPackage.PATIENT__PATIENT_BLOOD_PRESSURE:
        setPatient_blood_pressure(PATIENT_BLOOD_PRESSURE_EDEFAULT);
        return;
      case MyDslPackage.PATIENT__PULSE_RATE:
        setPulse_rate(PULSE_RATE_EDEFAULT);
        return;
      case MyDslPackage.PATIENT__SYMPTOMS:
        getSymptoms().clear();
        return;
      case MyDslPackage.PATIENT__MEDICINES:
        getMedicines().clear();
        return;
      case MyDslPackage.PATIENT__SUGAR_TESTS:
        getSugar_tests().clear();
        return;
      case MyDslPackage.PATIENT__DOCTORS:
        getDOCTORS().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PATIENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.PATIENT__PATIENT_GENDER:
        return PATIENT_GENDER_EDEFAULT == null ? patient_Gender != null : !PATIENT_GENDER_EDEFAULT.equals(patient_Gender);
      case MyDslPackage.PATIENT__PATIENT_AGE:
        return patient_Age != PATIENT_AGE_EDEFAULT;
      case MyDslPackage.PATIENT__PATIENT_HEIGHT:
        return PATIENT_HEIGHT_EDEFAULT == null ? patient_Height != null : !PATIENT_HEIGHT_EDEFAULT.equals(patient_Height);
      case MyDslPackage.PATIENT__PATIENT_WEIGHT:
        return PATIENT_WEIGHT_EDEFAULT == null ? patient_Weight != null : !PATIENT_WEIGHT_EDEFAULT.equals(patient_Weight);
      case MyDslPackage.PATIENT__PATIENT_BLOOD_PRESSURE:
        return patient_blood_pressure != PATIENT_BLOOD_PRESSURE_EDEFAULT;
      case MyDslPackage.PATIENT__PULSE_RATE:
        return pulse_rate != PULSE_RATE_EDEFAULT;
      case MyDslPackage.PATIENT__SYMPTOMS:
        return symptoms != null && !symptoms.isEmpty();
      case MyDslPackage.PATIENT__MEDICINES:
        return medicines != null && !medicines.isEmpty();
      case MyDslPackage.PATIENT__SUGAR_TESTS:
        return sugar_tests != null && !sugar_tests.isEmpty();
      case MyDslPackage.PATIENT__DOCTORS:
        return doctors != null && !doctors.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", Patient_Gender: ");
    result.append(patient_Gender);
    result.append(", Patient_Age: ");
    result.append(patient_Age);
    result.append(", Patient_Height: ");
    result.append(patient_Height);
    result.append(", Patient_Weight: ");
    result.append(patient_Weight);
    result.append(", patient_blood_pressure: ");
    result.append(patient_blood_pressure);
    result.append(", pulse_rate: ");
    result.append(pulse_rate);
    result.append(')');
    return result.toString();
  }

} //PatientImpl
