/*
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.ui.tests;

import assignment_2_ssda.xtext_ml.ass2.ui.internal.Ass2Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Ass2Activator.getInstance().getInjector("assignment_2_ssda.xtext_ml.ass2.MyDsl");
	}

}
