/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Genital thrush</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getGenital_thrush()
 * @model
 * @generated
 */
public interface Genital_thrush extends Symptom
{
} // Genital_thrush
