/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>J48 Classifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.J48Classifier#getSet_pruned_trees <em>Set pruned trees</em>}</li>
 * </ul>
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getJ48Classifier()
 * @model
 * @generated
 */
public interface J48Classifier extends Machine_learning_Algorithms
{
  /**
   * Returns the value of the '<em><b>Set pruned trees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set pruned trees</em>' attribute.
   * @see #setSet_pruned_trees(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getJ48Classifier_Set_pruned_trees()
   * @model
   * @generated
   */
  String getSet_pruned_trees();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.J48Classifier#getSet_pruned_trees <em>Set pruned trees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set pruned trees</em>' attribute.
   * @see #getSet_pruned_trees()
   * @generated
   */
  void setSet_pruned_trees(String value);

} // J48Classifier
