/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Machine learning Algorithms</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Machine_learning_Algorithms#getPredict_diabetes <em>Predict diabetes</em>}</li>
 * </ul>
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getMachine_learning_Algorithms()
 * @model
 * @generated
 */
public interface Machine_learning_Algorithms extends EObject
{
  /**
   * Returns the value of the '<em><b>Predict diabetes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predict diabetes</em>' containment reference.
   * @see #setPredict_diabetes(Predict_diabetes)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getMachine_learning_Algorithms_Predict_diabetes()
   * @model containment="true"
   * @generated
   */
  Predict_diabetes getPredict_diabetes();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Machine_learning_Algorithms#getPredict_diabetes <em>Predict diabetes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predict diabetes</em>' containment reference.
   * @see #getPredict_diabetes()
   * @generated
   */
  void setPredict_diabetes(Predict_diabetes value);

} // Machine_learning_Algorithms
