/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>muscle stiffness</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getmuscle_stiffness()
 * @model
 * @generated
 */
public interface muscle_stiffness extends Symptom
{
} // muscle_stiffness
