/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Diabetes Prediction System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Diabetes Prediction System</em>'.
   * @generated
   */
  Diabetes_Prediction_System createDiabetes_Prediction_System();

  /**
   * Returns a new object of class '<em>Medicines</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Medicines</em>'.
   * @generated
   */
  Medicines createMedicines();

  /**
   * Returns a new object of class '<em>Symptom</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Symptom</em>'.
   * @generated
   */
  Symptom createSymptom();

  /**
   * Returns a new object of class '<em>Polyuria</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Polyuria</em>'.
   * @generated
   */
  Polyuria createPolyuria();

  /**
   * Returns a new object of class '<em>Polydipsia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Polydipsia</em>'.
   * @generated
   */
  Polydipsia createPolydipsia();

  /**
   * Returns a new object of class '<em>sudden weight loss</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>sudden weight loss</em>'.
   * @generated
   */
  sudden_weight_loss createsudden_weight_loss();

  /**
   * Returns a new object of class '<em>Polyphagia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Polyphagia</em>'.
   * @generated
   */
  Polyphagia createPolyphagia();

  /**
   * Returns a new object of class '<em>Genital thrush</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Genital thrush</em>'.
   * @generated
   */
  Genital_thrush createGenital_thrush();

  /**
   * Returns a new object of class '<em>visual blurring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>visual blurring</em>'.
   * @generated
   */
  visual_blurring createvisual_blurring();

  /**
   * Returns a new object of class '<em>Itching</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Itching</em>'.
   * @generated
   */
  Itching createItching();

  /**
   * Returns a new object of class '<em>Irritability</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Irritability</em>'.
   * @generated
   */
  Irritability createIrritability();

  /**
   * Returns a new object of class '<em>delayed healing</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>delayed healing</em>'.
   * @generated
   */
  delayed_healing createdelayed_healing();

  /**
   * Returns a new object of class '<em>partial paresis</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>partial paresis</em>'.
   * @generated
   */
  partial_paresis createpartial_paresis();

  /**
   * Returns a new object of class '<em>muscle stiffness</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>muscle stiffness</em>'.
   * @generated
   */
  muscle_stiffness createmuscle_stiffness();

  /**
   * Returns a new object of class '<em>Alopecia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alopecia</em>'.
   * @generated
   */
  Alopecia createAlopecia();

  /**
   * Returns a new object of class '<em>Obesity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Obesity</em>'.
   * @generated
   */
  Obesity createObesity();

  /**
   * Returns a new object of class '<em>Sugar Test</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sugar Test</em>'.
   * @generated
   */
  Sugar_Test createSugar_Test();

  /**
   * Returns a new object of class '<em>Doctor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Doctor</em>'.
   * @generated
   */
  Doctor createDoctor();

  /**
   * Returns a new object of class '<em>Patient</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Patient</em>'.
   * @generated
   */
  Patient createPatient();

  /**
   * Returns a new object of class '<em>Predict diabetes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predict diabetes</em>'.
   * @generated
   */
  Predict_diabetes createPredict_diabetes();

  /**
   * Returns a new object of class '<em>Machine learning Algorithms</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Machine learning Algorithms</em>'.
   * @generated
   */
  Machine_learning_Algorithms createMachine_learning_Algorithms();

  /**
   * Returns a new object of class '<em>Random forest</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Random forest</em>'.
   * @generated
   */
  Random_forest createRandom_forest();

  /**
   * Returns a new object of class '<em>SVM Classifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SVM Classifier</em>'.
   * @generated
   */
  SVM_Classifier createSVM_Classifier();

  /**
   * Returns a new object of class '<em>J48 Classifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>J48 Classifier</em>'.
   * @generated
   */
  J48Classifier createJ48Classifier();

  /**
   * Returns a new object of class '<em>Navie Bayes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Navie Bayes</em>'.
   * @generated
   */
  NavieBayes createNavieBayes();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
