/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext_ml.assignment_2_ssda/ass2/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Diabetes_Prediction_SystemImpl <em>Diabetes Prediction System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Diabetes_Prediction_SystemImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getDiabetes_Prediction_System()
   * @generated
   */
  int DIABETES_PREDICTION_SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIABETES_PREDICTION_SYSTEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Medicines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIABETES_PREDICTION_SYSTEM__MEDICINES = 1;

  /**
   * The feature id for the '<em><b>Symptom</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIABETES_PREDICTION_SYSTEM__SYMPTOM = 2;

  /**
   * The feature id for the '<em><b>Doctors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIABETES_PREDICTION_SYSTEM__DOCTORS = 3;

  /**
   * The feature id for the '<em><b>Patient</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIABETES_PREDICTION_SYSTEM__PATIENT = 4;

  /**
   * The feature id for the '<em><b>Machine learning Algorithms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIABETES_PREDICTION_SYSTEM__MACHINE_LEARNING_ALGORITHMS = 5;

  /**
   * The number of structural features of the '<em>Diabetes Prediction System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIABETES_PREDICTION_SYSTEM_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MedicinesImpl <em>Medicines</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MedicinesImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getMedicines()
   * @generated
   */
  int MEDICINES = 1;

  /**
   * The feature id for the '<em><b>Medicine name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDICINES__MEDICINE_NAME = 0;

  /**
   * The feature id for the '<em><b>Medicine dossage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDICINES__MEDICINE_DOSSAGE = 1;

  /**
   * The number of structural features of the '<em>Medicines</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDICINES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SymptomImpl <em>Symptom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SymptomImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getSymptom()
   * @generated
   */
  int SYMPTOM = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYMPTOM__NAME = 0;

  /**
   * The number of structural features of the '<em>Symptom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYMPTOM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyuriaImpl <em>Polyuria</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyuriaImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPolyuria()
   * @generated
   */
  int POLYURIA = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLYURIA__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Polyuria</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLYURIA_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolydipsiaImpl <em>Polydipsia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolydipsiaImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPolydipsia()
   * @generated
   */
  int POLYDIPSIA = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLYDIPSIA__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Polydipsia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLYDIPSIA_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.sudden_weight_lossImpl <em>sudden weight loss</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.sudden_weight_lossImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getsudden_weight_loss()
   * @generated
   */
  int SUDDEN_WEIGHT_LOSS = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUDDEN_WEIGHT_LOSS__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>sudden weight loss</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUDDEN_WEIGHT_LOSS_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyphagiaImpl <em>Polyphagia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyphagiaImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPolyphagia()
   * @generated
   */
  int POLYPHAGIA = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLYPHAGIA__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Polyphagia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLYPHAGIA_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Genital_thrushImpl <em>Genital thrush</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Genital_thrushImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getGenital_thrush()
   * @generated
   */
  int GENITAL_THRUSH = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENITAL_THRUSH__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Genital thrush</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENITAL_THRUSH_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.visual_blurringImpl <em>visual blurring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.visual_blurringImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getvisual_blurring()
   * @generated
   */
  int VISUAL_BLURRING = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISUAL_BLURRING__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>visual blurring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISUAL_BLURRING_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ItchingImpl <em>Itching</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ItchingImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getItching()
   * @generated
   */
  int ITCHING = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITCHING__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Itching</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITCHING_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.IrritabilityImpl <em>Irritability</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.IrritabilityImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getIrritability()
   * @generated
   */
  int IRRITABILITY = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRRITABILITY__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Irritability</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRRITABILITY_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.delayed_healingImpl <em>delayed healing</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.delayed_healingImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getdelayed_healing()
   * @generated
   */
  int DELAYED_HEALING = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELAYED_HEALING__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>delayed healing</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELAYED_HEALING_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.partial_paresisImpl <em>partial paresis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.partial_paresisImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getpartial_paresis()
   * @generated
   */
  int PARTIAL_PARESIS = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIAL_PARESIS__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>partial paresis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTIAL_PARESIS_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.muscle_stiffnessImpl <em>muscle stiffness</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.muscle_stiffnessImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getmuscle_stiffness()
   * @generated
   */
  int MUSCLE_STIFFNESS = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUSCLE_STIFFNESS__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>muscle stiffness</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUSCLE_STIFFNESS_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.AlopeciaImpl <em>Alopecia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.AlopeciaImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getAlopecia()
   * @generated
   */
  int ALOPECIA = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALOPECIA__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Alopecia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALOPECIA_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ObesityImpl <em>Obesity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ObesityImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getObesity()
   * @generated
   */
  int OBESITY = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBESITY__NAME = SYMPTOM__NAME;

  /**
   * The number of structural features of the '<em>Obesity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBESITY_FEATURE_COUNT = SYMPTOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Sugar_TestImpl <em>Sugar Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Sugar_TestImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getSugar_Test()
   * @generated
   */
  int SUGAR_TEST = 16;

  /**
   * The feature id for the '<em><b>Previous blood sugar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUGAR_TEST__PREVIOUS_BLOOD_SUGAR = 0;

  /**
   * The feature id for the '<em><b>Current blood sugar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUGAR_TEST__CURRENT_BLOOD_SUGAR = 1;

  /**
   * The number of structural features of the '<em>Sugar Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUGAR_TEST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.DoctorImpl <em>Doctor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.DoctorImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getDoctor()
   * @generated
   */
  int DOCTOR = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Doctor specailization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCTOR__DOCTOR_SPECAILIZATION = 1;

  /**
   * The feature id for the '<em><b>Medicines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCTOR__MEDICINES = 2;

  /**
   * The feature id for the '<em><b>Symptoms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCTOR__SYMPTOMS = 3;

  /**
   * The number of structural features of the '<em>Doctor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCTOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl <em>Patient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPatient()
   * @generated
   */
  int PATIENT = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Patient Gender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__PATIENT_GENDER = 1;

  /**
   * The feature id for the '<em><b>Patient Age</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__PATIENT_AGE = 2;

  /**
   * The feature id for the '<em><b>Patient Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__PATIENT_HEIGHT = 3;

  /**
   * The feature id for the '<em><b>Patient Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__PATIENT_WEIGHT = 4;

  /**
   * The feature id for the '<em><b>Patient blood pressure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__PATIENT_BLOOD_PRESSURE = 5;

  /**
   * The feature id for the '<em><b>Pulse rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__PULSE_RATE = 6;

  /**
   * The feature id for the '<em><b>Symptoms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__SYMPTOMS = 7;

  /**
   * The feature id for the '<em><b>Medicines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__MEDICINES = 8;

  /**
   * The feature id for the '<em><b>Sugar tests</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__SUGAR_TESTS = 9;

  /**
   * The feature id for the '<em><b>DOCTORS</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT__DOCTORS = 10;

  /**
   * The number of structural features of the '<em>Patient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATIENT_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Predict_diabetesImpl <em>Predict diabetes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Predict_diabetesImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPredict_diabetes()
   * @generated
   */
  int PREDICT_DIABETES = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICT_DIABETES__NAME = 0;

  /**
   * The number of structural features of the '<em>Predict diabetes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICT_DIABETES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Machine_learning_AlgorithmsImpl <em>Machine learning Algorithms</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Machine_learning_AlgorithmsImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getMachine_learning_Algorithms()
   * @generated
   */
  int MACHINE_LEARNING_ALGORITHMS = 20;

  /**
   * The feature id for the '<em><b>Predict diabetes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_LEARNING_ALGORITHMS__PREDICT_DIABETES = 0;

  /**
   * The number of structural features of the '<em>Machine learning Algorithms</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Random_forestImpl <em>Random forest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Random_forestImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getRandom_forest()
   * @generated
   */
  int RANDOM_FOREST = 21;

  /**
   * The feature id for the '<em><b>Predict diabetes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FOREST__PREDICT_DIABETES = MACHINE_LEARNING_ALGORITHMS__PREDICT_DIABETES;

  /**
   * The feature id for the '<em><b>Create trees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FOREST__CREATE_TREES = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Random forest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FOREST_FEATURE_COUNT = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SVM_ClassifierImpl <em>SVM Classifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SVM_ClassifierImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getSVM_Classifier()
   * @generated
   */
  int SVM_CLASSIFIER = 22;

  /**
   * The feature id for the '<em><b>Predict diabetes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM_CLASSIFIER__PREDICT_DIABETES = MACHINE_LEARNING_ALGORITHMS__PREDICT_DIABETES;

  /**
   * The feature id for the '<em><b>Kernel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM_CLASSIFIER__KERNEL = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SVM Classifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM_CLASSIFIER_FEATURE_COUNT = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.J48ClassifierImpl <em>J48 Classifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.J48ClassifierImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getJ48Classifier()
   * @generated
   */
  int J48_CLASSIFIER = 23;

  /**
   * The feature id for the '<em><b>Predict diabetes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int J48_CLASSIFIER__PREDICT_DIABETES = MACHINE_LEARNING_ALGORITHMS__PREDICT_DIABETES;

  /**
   * The feature id for the '<em><b>Set pruned trees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int J48_CLASSIFIER__SET_PRUNED_TREES = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>J48 Classifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int J48_CLASSIFIER_FEATURE_COUNT = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.NavieBayesImpl <em>Navie Bayes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.NavieBayesImpl
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getNavieBayes()
   * @generated
   */
  int NAVIE_BAYES = 24;

  /**
   * The feature id for the '<em><b>Predict diabetes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIE_BAYES__PREDICT_DIABETES = MACHINE_LEARNING_ALGORITHMS__PREDICT_DIABETES;

  /**
   * The feature id for the '<em><b>Conditional Probability based</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIE_BAYES__CONDITIONAL_PROBABILITY_BASED = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Navie Bayes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIE_BAYES_FEATURE_COUNT = MACHINE_LEARNING_ALGORITHMS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System <em>Diabetes Prediction System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Diabetes Prediction System</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System
   * @generated
   */
  EClass getDiabetes_Prediction_System();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getName()
   * @see #getDiabetes_Prediction_System()
   * @generated
   */
  EAttribute getDiabetes_Prediction_System_Name();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getMedicines <em>Medicines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Medicines</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getMedicines()
   * @see #getDiabetes_Prediction_System()
   * @generated
   */
  EReference getDiabetes_Prediction_System_Medicines();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getSymptom <em>Symptom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Symptom</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getSymptom()
   * @see #getDiabetes_Prediction_System()
   * @generated
   */
  EReference getDiabetes_Prediction_System_Symptom();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getDoctors <em>Doctors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Doctors</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getDoctors()
   * @see #getDiabetes_Prediction_System()
   * @generated
   */
  EReference getDiabetes_Prediction_System_Doctors();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getPatient <em>Patient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Patient</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getPatient()
   * @see #getDiabetes_Prediction_System()
   * @generated
   */
  EReference getDiabetes_Prediction_System_Patient();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getMachine_learning_Algorithms <em>Machine learning Algorithms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Machine learning Algorithms</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Diabetes_Prediction_System#getMachine_learning_Algorithms()
   * @see #getDiabetes_Prediction_System()
   * @generated
   */
  EReference getDiabetes_Prediction_System_Machine_learning_Algorithms();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines <em>Medicines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Medicines</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines
   * @generated
   */
  EClass getMedicines();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines#getMedicine_name <em>Medicine name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Medicine name</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines#getMedicine_name()
   * @see #getMedicines()
   * @generated
   */
  EAttribute getMedicines_Medicine_name();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines#getMedicine_dossage <em>Medicine dossage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Medicine dossage</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines#getMedicine_dossage()
   * @see #getMedicines()
   * @generated
   */
  EAttribute getMedicines_Medicine_dossage();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Symptom <em>Symptom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Symptom</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Symptom
   * @generated
   */
  EClass getSymptom();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Symptom#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Symptom#getName()
   * @see #getSymptom()
   * @generated
   */
  EAttribute getSymptom_Name();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Polyuria <em>Polyuria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Polyuria</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Polyuria
   * @generated
   */
  EClass getPolyuria();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Polydipsia <em>Polydipsia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Polydipsia</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Polydipsia
   * @generated
   */
  EClass getPolydipsia();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.sudden_weight_loss <em>sudden weight loss</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>sudden weight loss</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.sudden_weight_loss
   * @generated
   */
  EClass getsudden_weight_loss();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Polyphagia <em>Polyphagia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Polyphagia</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Polyphagia
   * @generated
   */
  EClass getPolyphagia();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Genital_thrush <em>Genital thrush</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Genital thrush</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Genital_thrush
   * @generated
   */
  EClass getGenital_thrush();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.visual_blurring <em>visual blurring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>visual blurring</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.visual_blurring
   * @generated
   */
  EClass getvisual_blurring();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Itching <em>Itching</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Itching</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Itching
   * @generated
   */
  EClass getItching();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Irritability <em>Irritability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Irritability</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Irritability
   * @generated
   */
  EClass getIrritability();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.delayed_healing <em>delayed healing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>delayed healing</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.delayed_healing
   * @generated
   */
  EClass getdelayed_healing();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.partial_paresis <em>partial paresis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>partial paresis</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.partial_paresis
   * @generated
   */
  EClass getpartial_paresis();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.muscle_stiffness <em>muscle stiffness</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>muscle stiffness</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.muscle_stiffness
   * @generated
   */
  EClass getmuscle_stiffness();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Alopecia <em>Alopecia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alopecia</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Alopecia
   * @generated
   */
  EClass getAlopecia();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Obesity <em>Obesity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obesity</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Obesity
   * @generated
   */
  EClass getObesity();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test <em>Sugar Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sugar Test</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test
   * @generated
   */
  EClass getSugar_Test();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getPrevious_blood_sugar <em>Previous blood sugar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Previous blood sugar</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getPrevious_blood_sugar()
   * @see #getSugar_Test()
   * @generated
   */
  EAttribute getSugar_Test_Previous_blood_sugar();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getCurrent_blood_sugar <em>Current blood sugar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Current blood sugar</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getCurrent_blood_sugar()
   * @see #getSugar_Test()
   * @generated
   */
  EAttribute getSugar_Test_Current_blood_sugar();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor <em>Doctor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doctor</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor
   * @generated
   */
  EClass getDoctor();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getName()
   * @see #getDoctor()
   * @generated
   */
  EAttribute getDoctor_Name();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getDoctor_specailization <em>Doctor specailization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Doctor specailization</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getDoctor_specailization()
   * @see #getDoctor()
   * @generated
   */
  EAttribute getDoctor_Doctor_specailization();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getMedicines <em>Medicines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Medicines</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getMedicines()
   * @see #getDoctor()
   * @generated
   */
  EReference getDoctor_Medicines();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getSymptoms <em>Symptoms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Symptoms</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor#getSymptoms()
   * @see #getDoctor()
   * @generated
   */
  EReference getDoctor_Symptoms();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient <em>Patient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Patient</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient
   * @generated
   */
  EClass getPatient();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getName()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Name();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Gender <em>Patient Gender</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patient Gender</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Gender()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Patient_Gender();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Age <em>Patient Age</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patient Age</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Age()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Patient_Age();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Height <em>Patient Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patient Height</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Height()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Patient_Height();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Weight <em>Patient Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patient Weight</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Weight()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Patient_Weight();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_blood_pressure <em>Patient blood pressure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patient blood pressure</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_blood_pressure()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Patient_blood_pressure();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPulse_rate <em>Pulse rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pulse rate</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPulse_rate()
   * @see #getPatient()
   * @generated
   */
  EAttribute getPatient_Pulse_rate();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getSymptoms <em>Symptoms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Symptoms</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getSymptoms()
   * @see #getPatient()
   * @generated
   */
  EReference getPatient_Symptoms();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getMedicines <em>Medicines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Medicines</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getMedicines()
   * @see #getPatient()
   * @generated
   */
  EReference getPatient_Medicines();

  /**
   * Returns the meta object for the containment reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getSugar_tests <em>Sugar tests</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sugar tests</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getSugar_tests()
   * @see #getPatient()
   * @generated
   */
  EReference getPatient_Sugar_tests();

  /**
   * Returns the meta object for the reference list '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getDOCTORS <em>DOCTORS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>DOCTORS</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getDOCTORS()
   * @see #getPatient()
   * @generated
   */
  EReference getPatient_DOCTORS();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Predict_diabetes <em>Predict diabetes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predict diabetes</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Predict_diabetes
   * @generated
   */
  EClass getPredict_diabetes();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Predict_diabetes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Predict_diabetes#getName()
   * @see #getPredict_diabetes()
   * @generated
   */
  EAttribute getPredict_diabetes_Name();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Machine_learning_Algorithms <em>Machine learning Algorithms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Machine learning Algorithms</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Machine_learning_Algorithms
   * @generated
   */
  EClass getMachine_learning_Algorithms();

  /**
   * Returns the meta object for the containment reference '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Machine_learning_Algorithms#getPredict_diabetes <em>Predict diabetes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predict diabetes</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Machine_learning_Algorithms#getPredict_diabetes()
   * @see #getMachine_learning_Algorithms()
   * @generated
   */
  EReference getMachine_learning_Algorithms_Predict_diabetes();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Random_forest <em>Random forest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Random forest</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Random_forest
   * @generated
   */
  EClass getRandom_forest();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Random_forest#getCreate_trees <em>Create trees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Create trees</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.Random_forest#getCreate_trees()
   * @see #getRandom_forest()
   * @generated
   */
  EAttribute getRandom_forest_Create_trees();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.SVM_Classifier <em>SVM Classifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SVM Classifier</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.SVM_Classifier
   * @generated
   */
  EClass getSVM_Classifier();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.SVM_Classifier#getKernel <em>Kernel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kernel</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.SVM_Classifier#getKernel()
   * @see #getSVM_Classifier()
   * @generated
   */
  EAttribute getSVM_Classifier_Kernel();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.J48Classifier <em>J48 Classifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>J48 Classifier</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.J48Classifier
   * @generated
   */
  EClass getJ48Classifier();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.J48Classifier#getSet_pruned_trees <em>Set pruned trees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Set pruned trees</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.J48Classifier#getSet_pruned_trees()
   * @see #getJ48Classifier()
   * @generated
   */
  EAttribute getJ48Classifier_Set_pruned_trees();

  /**
   * Returns the meta object for class '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.NavieBayes <em>Navie Bayes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Navie Bayes</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.NavieBayes
   * @generated
   */
  EClass getNavieBayes();

  /**
   * Returns the meta object for the attribute '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.NavieBayes#getConditional_Probability_based <em>Conditional Probability based</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Conditional Probability based</em>'.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.NavieBayes#getConditional_Probability_based()
   * @see #getNavieBayes()
   * @generated
   */
  EAttribute getNavieBayes_Conditional_Probability_based();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Diabetes_Prediction_SystemImpl <em>Diabetes Prediction System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Diabetes_Prediction_SystemImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getDiabetes_Prediction_System()
     * @generated
     */
    EClass DIABETES_PREDICTION_SYSTEM = eINSTANCE.getDiabetes_Prediction_System();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIABETES_PREDICTION_SYSTEM__NAME = eINSTANCE.getDiabetes_Prediction_System_Name();

    /**
     * The meta object literal for the '<em><b>Medicines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIABETES_PREDICTION_SYSTEM__MEDICINES = eINSTANCE.getDiabetes_Prediction_System_Medicines();

    /**
     * The meta object literal for the '<em><b>Symptom</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIABETES_PREDICTION_SYSTEM__SYMPTOM = eINSTANCE.getDiabetes_Prediction_System_Symptom();

    /**
     * The meta object literal for the '<em><b>Doctors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIABETES_PREDICTION_SYSTEM__DOCTORS = eINSTANCE.getDiabetes_Prediction_System_Doctors();

    /**
     * The meta object literal for the '<em><b>Patient</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIABETES_PREDICTION_SYSTEM__PATIENT = eINSTANCE.getDiabetes_Prediction_System_Patient();

    /**
     * The meta object literal for the '<em><b>Machine learning Algorithms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIABETES_PREDICTION_SYSTEM__MACHINE_LEARNING_ALGORITHMS = eINSTANCE.getDiabetes_Prediction_System_Machine_learning_Algorithms();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MedicinesImpl <em>Medicines</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MedicinesImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getMedicines()
     * @generated
     */
    EClass MEDICINES = eINSTANCE.getMedicines();

    /**
     * The meta object literal for the '<em><b>Medicine name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDICINES__MEDICINE_NAME = eINSTANCE.getMedicines_Medicine_name();

    /**
     * The meta object literal for the '<em><b>Medicine dossage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDICINES__MEDICINE_DOSSAGE = eINSTANCE.getMedicines_Medicine_dossage();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SymptomImpl <em>Symptom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SymptomImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getSymptom()
     * @generated
     */
    EClass SYMPTOM = eINSTANCE.getSymptom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYMPTOM__NAME = eINSTANCE.getSymptom_Name();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyuriaImpl <em>Polyuria</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyuriaImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPolyuria()
     * @generated
     */
    EClass POLYURIA = eINSTANCE.getPolyuria();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolydipsiaImpl <em>Polydipsia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolydipsiaImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPolydipsia()
     * @generated
     */
    EClass POLYDIPSIA = eINSTANCE.getPolydipsia();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.sudden_weight_lossImpl <em>sudden weight loss</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.sudden_weight_lossImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getsudden_weight_loss()
     * @generated
     */
    EClass SUDDEN_WEIGHT_LOSS = eINSTANCE.getsudden_weight_loss();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyphagiaImpl <em>Polyphagia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PolyphagiaImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPolyphagia()
     * @generated
     */
    EClass POLYPHAGIA = eINSTANCE.getPolyphagia();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Genital_thrushImpl <em>Genital thrush</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Genital_thrushImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getGenital_thrush()
     * @generated
     */
    EClass GENITAL_THRUSH = eINSTANCE.getGenital_thrush();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.visual_blurringImpl <em>visual blurring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.visual_blurringImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getvisual_blurring()
     * @generated
     */
    EClass VISUAL_BLURRING = eINSTANCE.getvisual_blurring();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ItchingImpl <em>Itching</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ItchingImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getItching()
     * @generated
     */
    EClass ITCHING = eINSTANCE.getItching();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.IrritabilityImpl <em>Irritability</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.IrritabilityImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getIrritability()
     * @generated
     */
    EClass IRRITABILITY = eINSTANCE.getIrritability();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.delayed_healingImpl <em>delayed healing</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.delayed_healingImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getdelayed_healing()
     * @generated
     */
    EClass DELAYED_HEALING = eINSTANCE.getdelayed_healing();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.partial_paresisImpl <em>partial paresis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.partial_paresisImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getpartial_paresis()
     * @generated
     */
    EClass PARTIAL_PARESIS = eINSTANCE.getpartial_paresis();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.muscle_stiffnessImpl <em>muscle stiffness</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.muscle_stiffnessImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getmuscle_stiffness()
     * @generated
     */
    EClass MUSCLE_STIFFNESS = eINSTANCE.getmuscle_stiffness();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.AlopeciaImpl <em>Alopecia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.AlopeciaImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getAlopecia()
     * @generated
     */
    EClass ALOPECIA = eINSTANCE.getAlopecia();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ObesityImpl <em>Obesity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.ObesityImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getObesity()
     * @generated
     */
    EClass OBESITY = eINSTANCE.getObesity();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Sugar_TestImpl <em>Sugar Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Sugar_TestImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getSugar_Test()
     * @generated
     */
    EClass SUGAR_TEST = eINSTANCE.getSugar_Test();

    /**
     * The meta object literal for the '<em><b>Previous blood sugar</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUGAR_TEST__PREVIOUS_BLOOD_SUGAR = eINSTANCE.getSugar_Test_Previous_blood_sugar();

    /**
     * The meta object literal for the '<em><b>Current blood sugar</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUGAR_TEST__CURRENT_BLOOD_SUGAR = eINSTANCE.getSugar_Test_Current_blood_sugar();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.DoctorImpl <em>Doctor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.DoctorImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getDoctor()
     * @generated
     */
    EClass DOCTOR = eINSTANCE.getDoctor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCTOR__NAME = eINSTANCE.getDoctor_Name();

    /**
     * The meta object literal for the '<em><b>Doctor specailization</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCTOR__DOCTOR_SPECAILIZATION = eINSTANCE.getDoctor_Doctor_specailization();

    /**
     * The meta object literal for the '<em><b>Medicines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCTOR__MEDICINES = eINSTANCE.getDoctor_Medicines();

    /**
     * The meta object literal for the '<em><b>Symptoms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCTOR__SYMPTOMS = eINSTANCE.getDoctor_Symptoms();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl <em>Patient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.PatientImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPatient()
     * @generated
     */
    EClass PATIENT = eINSTANCE.getPatient();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__NAME = eINSTANCE.getPatient_Name();

    /**
     * The meta object literal for the '<em><b>Patient Gender</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__PATIENT_GENDER = eINSTANCE.getPatient_Patient_Gender();

    /**
     * The meta object literal for the '<em><b>Patient Age</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__PATIENT_AGE = eINSTANCE.getPatient_Patient_Age();

    /**
     * The meta object literal for the '<em><b>Patient Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__PATIENT_HEIGHT = eINSTANCE.getPatient_Patient_Height();

    /**
     * The meta object literal for the '<em><b>Patient Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__PATIENT_WEIGHT = eINSTANCE.getPatient_Patient_Weight();

    /**
     * The meta object literal for the '<em><b>Patient blood pressure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__PATIENT_BLOOD_PRESSURE = eINSTANCE.getPatient_Patient_blood_pressure();

    /**
     * The meta object literal for the '<em><b>Pulse rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATIENT__PULSE_RATE = eINSTANCE.getPatient_Pulse_rate();

    /**
     * The meta object literal for the '<em><b>Symptoms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATIENT__SYMPTOMS = eINSTANCE.getPatient_Symptoms();

    /**
     * The meta object literal for the '<em><b>Medicines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATIENT__MEDICINES = eINSTANCE.getPatient_Medicines();

    /**
     * The meta object literal for the '<em><b>Sugar tests</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATIENT__SUGAR_TESTS = eINSTANCE.getPatient_Sugar_tests();

    /**
     * The meta object literal for the '<em><b>DOCTORS</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATIENT__DOCTORS = eINSTANCE.getPatient_DOCTORS();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Predict_diabetesImpl <em>Predict diabetes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Predict_diabetesImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getPredict_diabetes()
     * @generated
     */
    EClass PREDICT_DIABETES = eINSTANCE.getPredict_diabetes();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICT_DIABETES__NAME = eINSTANCE.getPredict_diabetes_Name();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Machine_learning_AlgorithmsImpl <em>Machine learning Algorithms</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Machine_learning_AlgorithmsImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getMachine_learning_Algorithms()
     * @generated
     */
    EClass MACHINE_LEARNING_ALGORITHMS = eINSTANCE.getMachine_learning_Algorithms();

    /**
     * The meta object literal for the '<em><b>Predict diabetes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MACHINE_LEARNING_ALGORITHMS__PREDICT_DIABETES = eINSTANCE.getMachine_learning_Algorithms_Predict_diabetes();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Random_forestImpl <em>Random forest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.Random_forestImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getRandom_forest()
     * @generated
     */
    EClass RANDOM_FOREST = eINSTANCE.getRandom_forest();

    /**
     * The meta object literal for the '<em><b>Create trees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANDOM_FOREST__CREATE_TREES = eINSTANCE.getRandom_forest_Create_trees();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SVM_ClassifierImpl <em>SVM Classifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.SVM_ClassifierImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getSVM_Classifier()
     * @generated
     */
    EClass SVM_CLASSIFIER = eINSTANCE.getSVM_Classifier();

    /**
     * The meta object literal for the '<em><b>Kernel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SVM_CLASSIFIER__KERNEL = eINSTANCE.getSVM_Classifier_Kernel();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.J48ClassifierImpl <em>J48 Classifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.J48ClassifierImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getJ48Classifier()
     * @generated
     */
    EClass J48_CLASSIFIER = eINSTANCE.getJ48Classifier();

    /**
     * The meta object literal for the '<em><b>Set pruned trees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute J48_CLASSIFIER__SET_PRUNED_TREES = eINSTANCE.getJ48Classifier_Set_pruned_trees();

    /**
     * The meta object literal for the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.impl.NavieBayesImpl <em>Navie Bayes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.NavieBayesImpl
     * @see assignment_2_ssda.xtext_ml.ass2.myDsl.impl.MyDslPackageImpl#getNavieBayes()
     * @generated
     */
    EClass NAVIE_BAYES = eINSTANCE.getNavieBayes();

    /**
     * The meta object literal for the '<em><b>Conditional Probability based</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAVIE_BAYES__CONDITIONAL_PROBABILITY_BASED = eINSTANCE.getNavieBayes_Conditional_Probability_based();

  }

} //MyDslPackage
