/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Navie Bayes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.NavieBayes#getConditional_Probability_based <em>Conditional Probability based</em>}</li>
 * </ul>
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getNavieBayes()
 * @model
 * @generated
 */
public interface NavieBayes extends Machine_learning_Algorithms
{
  /**
   * Returns the value of the '<em><b>Conditional Probability based</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditional Probability based</em>' attribute.
   * @see #setConditional_Probability_based(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getNavieBayes_Conditional_Probability_based()
   * @model
   * @generated
   */
  String getConditional_Probability_based();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.NavieBayes#getConditional_Probability_based <em>Conditional Probability based</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditional Probability based</em>' attribute.
   * @see #getConditional_Probability_based()
   * @generated
   */
  void setConditional_Probability_based(String value);

} // NavieBayes
