/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obesity</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getObesity()
 * @model
 * @generated
 */
public interface Obesity extends Symptom
{
} // Obesity
