/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Patient</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getName <em>Name</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Gender <em>Patient Gender</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Age <em>Patient Age</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Height <em>Patient Height</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Weight <em>Patient Weight</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_blood_pressure <em>Patient blood pressure</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPulse_rate <em>Pulse rate</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getSymptoms <em>Symptoms</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getMedicines <em>Medicines</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getSugar_tests <em>Sugar tests</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getDOCTORS <em>DOCTORS</em>}</li>
 * </ul>
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient()
 * @model
 * @generated
 */
public interface Patient extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Patient Gender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient Gender</em>' attribute.
   * @see #setPatient_Gender(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Patient_Gender()
   * @model
   * @generated
   */
  String getPatient_Gender();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Gender <em>Patient Gender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Patient Gender</em>' attribute.
   * @see #getPatient_Gender()
   * @generated
   */
  void setPatient_Gender(String value);

  /**
   * Returns the value of the '<em><b>Patient Age</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient Age</em>' attribute.
   * @see #setPatient_Age(int)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Patient_Age()
   * @model
   * @generated
   */
  int getPatient_Age();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Age <em>Patient Age</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Patient Age</em>' attribute.
   * @see #getPatient_Age()
   * @generated
   */
  void setPatient_Age(int value);

  /**
   * Returns the value of the '<em><b>Patient Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient Height</em>' attribute.
   * @see #setPatient_Height(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Patient_Height()
   * @model
   * @generated
   */
  String getPatient_Height();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Height <em>Patient Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Patient Height</em>' attribute.
   * @see #getPatient_Height()
   * @generated
   */
  void setPatient_Height(String value);

  /**
   * Returns the value of the '<em><b>Patient Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient Weight</em>' attribute.
   * @see #setPatient_Weight(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Patient_Weight()
   * @model
   * @generated
   */
  String getPatient_Weight();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_Weight <em>Patient Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Patient Weight</em>' attribute.
   * @see #getPatient_Weight()
   * @generated
   */
  void setPatient_Weight(String value);

  /**
   * Returns the value of the '<em><b>Patient blood pressure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient blood pressure</em>' attribute.
   * @see #setPatient_blood_pressure(int)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Patient_blood_pressure()
   * @model
   * @generated
   */
  int getPatient_blood_pressure();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPatient_blood_pressure <em>Patient blood pressure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Patient blood pressure</em>' attribute.
   * @see #getPatient_blood_pressure()
   * @generated
   */
  void setPatient_blood_pressure(int value);

  /**
   * Returns the value of the '<em><b>Pulse rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pulse rate</em>' attribute.
   * @see #setPulse_rate(int)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Pulse_rate()
   * @model
   * @generated
   */
  int getPulse_rate();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Patient#getPulse_rate <em>Pulse rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pulse rate</em>' attribute.
   * @see #getPulse_rate()
   * @generated
   */
  void setPulse_rate(int value);

  /**
   * Returns the value of the '<em><b>Symptoms</b></em>' containment reference list.
   * The list contents are of type {@link assignment_2_ssda.xtext_ml.ass2.myDsl.Symptom}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symptoms</em>' containment reference list.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Symptoms()
   * @model containment="true"
   * @generated
   */
  EList<Symptom> getSymptoms();

  /**
   * Returns the value of the '<em><b>Medicines</b></em>' containment reference list.
   * The list contents are of type {@link assignment_2_ssda.xtext_ml.ass2.myDsl.Medicines}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medicines</em>' containment reference list.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Medicines()
   * @model containment="true"
   * @generated
   */
  EList<Medicines> getMedicines();

  /**
   * Returns the value of the '<em><b>Sugar tests</b></em>' containment reference list.
   * The list contents are of type {@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sugar tests</em>' containment reference list.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_Sugar_tests()
   * @model containment="true"
   * @generated
   */
  EList<Sugar_Test> getSugar_tests();

  /**
   * Returns the value of the '<em><b>DOCTORS</b></em>' reference list.
   * The list contents are of type {@link assignment_2_ssda.xtext_ml.ass2.myDsl.Doctor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>DOCTORS</em>' reference list.
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getPatient_DOCTORS()
   * @model
   * @generated
   */
  EList<Doctor> getDOCTORS();

} // Patient
