/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Random forest</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Random_forest#getCreate_trees <em>Create trees</em>}</li>
 * </ul>
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getRandom_forest()
 * @model
 * @generated
 */
public interface Random_forest extends Machine_learning_Algorithms
{
  /**
   * Returns the value of the '<em><b>Create trees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Create trees</em>' attribute.
   * @see #setCreate_trees(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getRandom_forest_Create_trees()
   * @model
   * @generated
   */
  String getCreate_trees();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Random_forest#getCreate_trees <em>Create trees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Create trees</em>' attribute.
   * @see #getCreate_trees()
   * @generated
   */
  void setCreate_trees(String value);

} // Random_forest
