/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>sudden weight loss</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getsudden_weight_loss()
 * @model
 * @generated
 */
public interface sudden_weight_loss extends Symptom
{
} // sudden_weight_loss
