/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sugar Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getPrevious_blood_sugar <em>Previous blood sugar</em>}</li>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getCurrent_blood_sugar <em>Current blood sugar</em>}</li>
 * </ul>
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getSugar_Test()
 * @model
 * @generated
 */
public interface Sugar_Test extends EObject
{
  /**
   * Returns the value of the '<em><b>Previous blood sugar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Previous blood sugar</em>' attribute.
   * @see #setPrevious_blood_sugar(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getSugar_Test_Previous_blood_sugar()
   * @model
   * @generated
   */
  String getPrevious_blood_sugar();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getPrevious_blood_sugar <em>Previous blood sugar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Previous blood sugar</em>' attribute.
   * @see #getPrevious_blood_sugar()
   * @generated
   */
  void setPrevious_blood_sugar(String value);

  /**
   * Returns the value of the '<em><b>Current blood sugar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current blood sugar</em>' attribute.
   * @see #setCurrent_blood_sugar(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getSugar_Test_Current_blood_sugar()
   * @model
   * @generated
   */
  String getCurrent_blood_sugar();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.Sugar_Test#getCurrent_blood_sugar <em>Current blood sugar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current blood sugar</em>' attribute.
   * @see #getCurrent_blood_sugar()
   * @generated
   */
  void setCurrent_blood_sugar(String value);

} // Sugar_Test
