/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SVM Classifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment_2_ssda.xtext_ml.ass2.myDsl.SVM_Classifier#getKernel <em>Kernel</em>}</li>
 * </ul>
 *
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getSVM_Classifier()
 * @model
 * @generated
 */
public interface SVM_Classifier extends Machine_learning_Algorithms
{
  /**
   * Returns the value of the '<em><b>Kernel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kernel</em>' attribute.
   * @see #setKernel(String)
   * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage#getSVM_Classifier_Kernel()
   * @model
   * @generated
   */
  String getKernel();

  /**
   * Sets the value of the '{@link assignment_2_ssda.xtext_ml.ass2.myDsl.SVM_Classifier#getKernel <em>Kernel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kernel</em>' attribute.
   * @see #getKernel()
   * @generated
   */
  void setKernel(String value);

} // SVM_Classifier
