/*
 * generated by Xtext 2.25.0
 */
package assignment_2_ssda.xtext_ml.ass2.ide;


/**
 * Use this class to register ide components.
 */
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
