/*
 * generated by Xtext 2.25.0
 */
package assignment_2_ssda.xtext_ml.ass2.ide;

import assignment_2_ssda.xtext_ml.ass2.MyDslRuntimeModule;
import assignment_2_ssda.xtext_ml.ass2.MyDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDslIdeSetup extends MyDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule(), new MyDslIdeModule()));
	}
	
}
