/**
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.myDsl.util;

import assignment_2_ssda.xtext_ml.ass2.myDsl.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see assignment_2_ssda.xtext_ml.ass2.myDsl.MyDslPackage
 * @generated
 */
public class MyDslSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MyDslPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyDslSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = MyDslPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case MyDslPackage.DIABETES_PREDICTION_SYSTEM:
      {
        Diabetes_Prediction_System diabetes_Prediction_System = (Diabetes_Prediction_System)theEObject;
        T result = caseDiabetes_Prediction_System(diabetes_Prediction_System);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.MEDICINES:
      {
        Medicines medicines = (Medicines)theEObject;
        T result = caseMedicines(medicines);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.SYMPTOM:
      {
        Symptom symptom = (Symptom)theEObject;
        T result = caseSymptom(symptom);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.POLYURIA:
      {
        Polyuria polyuria = (Polyuria)theEObject;
        T result = casePolyuria(polyuria);
        if (result == null) result = caseSymptom(polyuria);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.POLYDIPSIA:
      {
        Polydipsia polydipsia = (Polydipsia)theEObject;
        T result = casePolydipsia(polydipsia);
        if (result == null) result = caseSymptom(polydipsia);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.SUDDEN_WEIGHT_LOSS:
      {
        sudden_weight_loss sudden_weight_loss = (sudden_weight_loss)theEObject;
        T result = casesudden_weight_loss(sudden_weight_loss);
        if (result == null) result = caseSymptom(sudden_weight_loss);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.POLYPHAGIA:
      {
        Polyphagia polyphagia = (Polyphagia)theEObject;
        T result = casePolyphagia(polyphagia);
        if (result == null) result = caseSymptom(polyphagia);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.GENITAL_THRUSH:
      {
        Genital_thrush genital_thrush = (Genital_thrush)theEObject;
        T result = caseGenital_thrush(genital_thrush);
        if (result == null) result = caseSymptom(genital_thrush);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.VISUAL_BLURRING:
      {
        visual_blurring visual_blurring = (visual_blurring)theEObject;
        T result = casevisual_blurring(visual_blurring);
        if (result == null) result = caseSymptom(visual_blurring);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.ITCHING:
      {
        Itching itching = (Itching)theEObject;
        T result = caseItching(itching);
        if (result == null) result = caseSymptom(itching);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.IRRITABILITY:
      {
        Irritability irritability = (Irritability)theEObject;
        T result = caseIrritability(irritability);
        if (result == null) result = caseSymptom(irritability);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.DELAYED_HEALING:
      {
        delayed_healing delayed_healing = (delayed_healing)theEObject;
        T result = casedelayed_healing(delayed_healing);
        if (result == null) result = caseSymptom(delayed_healing);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.PARTIAL_PARESIS:
      {
        partial_paresis partial_paresis = (partial_paresis)theEObject;
        T result = casepartial_paresis(partial_paresis);
        if (result == null) result = caseSymptom(partial_paresis);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.MUSCLE_STIFFNESS:
      {
        muscle_stiffness muscle_stiffness = (muscle_stiffness)theEObject;
        T result = casemuscle_stiffness(muscle_stiffness);
        if (result == null) result = caseSymptom(muscle_stiffness);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.ALOPECIA:
      {
        Alopecia alopecia = (Alopecia)theEObject;
        T result = caseAlopecia(alopecia);
        if (result == null) result = caseSymptom(alopecia);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.OBESITY:
      {
        Obesity obesity = (Obesity)theEObject;
        T result = caseObesity(obesity);
        if (result == null) result = caseSymptom(obesity);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.SUGAR_TEST:
      {
        Sugar_Test sugar_Test = (Sugar_Test)theEObject;
        T result = caseSugar_Test(sugar_Test);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.DOCTOR:
      {
        Doctor doctor = (Doctor)theEObject;
        T result = caseDoctor(doctor);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.PATIENT:
      {
        Patient patient = (Patient)theEObject;
        T result = casePatient(patient);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.PREDICT_DIABETES:
      {
        Predict_diabetes predict_diabetes = (Predict_diabetes)theEObject;
        T result = casePredict_diabetes(predict_diabetes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.MACHINE_LEARNING_ALGORITHMS:
      {
        Machine_learning_Algorithms machine_learning_Algorithms = (Machine_learning_Algorithms)theEObject;
        T result = caseMachine_learning_Algorithms(machine_learning_Algorithms);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.RANDOM_FOREST:
      {
        Random_forest random_forest = (Random_forest)theEObject;
        T result = caseRandom_forest(random_forest);
        if (result == null) result = caseMachine_learning_Algorithms(random_forest);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.SVM_CLASSIFIER:
      {
        SVM_Classifier svM_Classifier = (SVM_Classifier)theEObject;
        T result = caseSVM_Classifier(svM_Classifier);
        if (result == null) result = caseMachine_learning_Algorithms(svM_Classifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.J48_CLASSIFIER:
      {
        J48Classifier j48Classifier = (J48Classifier)theEObject;
        T result = caseJ48Classifier(j48Classifier);
        if (result == null) result = caseMachine_learning_Algorithms(j48Classifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyDslPackage.NAVIE_BAYES:
      {
        NavieBayes navieBayes = (NavieBayes)theEObject;
        T result = caseNavieBayes(navieBayes);
        if (result == null) result = caseMachine_learning_Algorithms(navieBayes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Diabetes Prediction System</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Diabetes Prediction System</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDiabetes_Prediction_System(Diabetes_Prediction_System object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Medicines</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Medicines</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMedicines(Medicines object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Symptom</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Symptom</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSymptom(Symptom object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Polyuria</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Polyuria</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePolyuria(Polyuria object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Polydipsia</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Polydipsia</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePolydipsia(Polydipsia object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>sudden weight loss</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>sudden weight loss</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casesudden_weight_loss(sudden_weight_loss object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Polyphagia</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Polyphagia</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePolyphagia(Polyphagia object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Genital thrush</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Genital thrush</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseGenital_thrush(Genital_thrush object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>visual blurring</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>visual blurring</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casevisual_blurring(visual_blurring object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Itching</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Itching</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseItching(Itching object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Irritability</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Irritability</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIrritability(Irritability object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>delayed healing</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>delayed healing</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casedelayed_healing(delayed_healing object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>partial paresis</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>partial paresis</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casepartial_paresis(partial_paresis object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>muscle stiffness</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>muscle stiffness</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casemuscle_stiffness(muscle_stiffness object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Alopecia</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Alopecia</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAlopecia(Alopecia object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Obesity</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Obesity</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseObesity(Obesity object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sugar Test</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sugar Test</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSugar_Test(Sugar_Test object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Doctor</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Doctor</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDoctor(Doctor object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Patient</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Patient</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePatient(Patient object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Predict diabetes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Predict diabetes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePredict_diabetes(Predict_diabetes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Machine learning Algorithms</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Machine learning Algorithms</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMachine_learning_Algorithms(Machine_learning_Algorithms object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Random forest</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Random forest</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRandom_forest(Random_forest object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>SVM Classifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>SVM Classifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSVM_Classifier(SVM_Classifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>J48 Classifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>J48 Classifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseJ48Classifier(J48Classifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Navie Bayes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Navie Bayes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNavieBayes(NavieBayes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //MyDslSwitch
