/*
 * generated by Xtext 2.26.0
 */
package assignment_2_ssda.xtext_ml.ass2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
